export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const TAGS_LOADED_REQUEST = 'TAGS_LOADED_REQUEST';
export const TAGS_LOADED_SUCCESS = 'TAGS_LOADED_SUCCESS';
export const TAGS_LOADED_FAILURE = 'TAGS_LOADED_FAILURE';

export const PRODUCT_CREATED_REQUEST = 'PRODUCT_CREATED_REQUEST';
export const PRODUCT_CREATED_SUCCESS = 'PRODUCT_CREATED_SUCCESS';
export const PRODUCT_CREATED_FAILURE = 'PRODUCT_CREATED_FAILURE';

export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST';
export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS';
export const PRODUCT_DETAIL_FAILURE = 'PRODUCT_DETAIL_FAILURE';

export const PRODUCT_DELETED_REQUEST = 'PRODUCT_DELETED_REQUEST';
export const PRODUCT_DELETED_SUCCESS = 'PRODUCT_DELETED_SUCCESS';
export const PRODUCT_DELETED_FAILURE = 'PRODUCT_DELETED_FAILURE';

export const PRODUCTS_LOADED_REQUEST = 'PRODUCTS_LOADED_REQUEST';
export const PRODUCTS_LOADED_SUCCESS = 'PRODUCTS_LOADED_SUCCESS';
export const PRODUCTS_LOADED_FAILURE = 'PRODUCTS_LOADED_FAILURE';

export const UI_RESET_ERROR = 'UI_RESET_ERROR';
